name: FriendlyWall
author: Tsunko
version: 1.1.8e
main: com.tenko.FriendlyWall
depend: [PluginManager]

permissions:
 friendlywall.minecartlogger.ignore:
    description: Ignore minecart logging.
    default: op