name: HermesIP
author: Tsunko
version: 0.1
main: com.tenko.HermesIP

commands:
    hreload:
        usage: /hreload
        description: Reloads the config.
    ipban:
        usage: /ipban [ip]
        description: Bans the designated IP.
    pardonip:
        usage: /pardonip [ip]
        description: Pardons the designated IP.
    iplist:
        usage: /iplist
        description: Lists all currently banned IPs and range IP bans.