name: FriendlyWall
author: Tsunko
version: 0.1.6
main: com.tenko.FriendlyWall
depend: [PluginManager]

permissions:
 friendlywall.minecartlogger.ignore:
    description: Ignore minecart logging.
    default: op